; Listing generated by Microsoft (R) Optimizing Compiler Version 19.33.31630.0 

	TITLE	d:\учеба\constructure of software\labs\spring semester\lab01, 03\lab01\lab01\release\getbirthdaynumber.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

PUBLIC	??_C@_0CL@OIGHMCJH@Enter?5you?5Birthday?5data?5in?5form@ ; `string'
EXTRN	__imp_??5?$basic_istream@DU?$char_traits@D@std@@@std@@QAEAAV01@AAH@Z:PROC
EXTRN	__imp_?cin@std@@3V?$basic_istream@DU?$char_traits@D@std@@@1@A:BYTE
;	COMDAT ??_C@_0CL@OIGHMCJH@Enter?5you?5Birthday?5data?5in?5form@
CONST	SEGMENT
??_C@_0CL@OIGHMCJH@Enter?5you?5Birthday?5data?5in?5form@ DB 'Enter you Bi'
	DB	'rthday data in format ', 0c4H, 0c4H, 0ccH, 0ccH, 0c3H, 0c3H, 0c3H
	DB	0c3H, 00H					; `string'
?_Fake_alloc@std@@3U_Fake_allocator@1@B	ORG $+1		; std::_Fake_alloc
PUBLIC	?getBirthdayNumber@@YAHHHHH@Z			; getBirthdayNumber
END
