; Listing generated by Microsoft (R) Optimizing Compiler Version 19.33.31630.0 

	TITLE	d:\учеба\constructure of software\labs\spring semester\lab01, 03\lab01\lab01\release\getnumber.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

PUBLIC	?getNumber@@YAHHHHH@Z				; getNumber
END
